import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Navbar from '../pages/components/Navbar';
import Footer from '../pages/components/Footer';
import Section from '../pages/components/Section';

export default function Home() {
  return (
    <>
      <Head>
        <title>moon.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.navbar}>
          <Navbar />
        </div>
        <div className={styles.section}>
          <Section />
        </div>
        <div className={styles.footer}>
          <Footer/>
        </div>
      </main>
    </>
  )
}
